/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ScholarshipsCompareRouteImport } from './routes/scholarships/compare'
import { Route as ScholarshipsClosingSoonRouteImport } from './routes/scholarships/closing-soon'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships/$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ScholarshipsDegreeDegreeRouteImport } from './routes/scholarships/degree/$degree'
import { Route as ScholarshipsCountryCountryRouteImport } from './routes/scholarships/country/$country'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ScholarshipsCompareRoute = ScholarshipsCompareRouteImport.update({
  id: '/scholarships/compare',
  path: '/scholarships/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsClosingSoonRoute = ScholarshipsClosingSoonRouteImport.update({
  id: '/scholarships/closing-soon',
  path: '/scholarships/closing-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/scholarships/$slug',
  path: '/scholarships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsDegreeDegreeRoute =
  ScholarshipsDegreeDegreeRouteImport.update({
    id: '/scholarships/degree/$degree',
    path: '/scholarships/degree/$degree',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScholarshipsCountryCountryRoute =
  ScholarshipsCountryCountryRouteImport.update({
    id: '/scholarships/country/$country',
    path: '/scholarships/country/$country',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/scholarships/closing-soon': typeof ScholarshipsClosingSoonRoute
  '/scholarships/compare': typeof ScholarshipsCompareRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/scholarships/country/$country': typeof ScholarshipsCountryCountryRoute
  '/scholarships/degree/$degree': typeof ScholarshipsDegreeDegreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/og': typeof ApiOgRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/scholarships/closing-soon': typeof ScholarshipsClosingSoonRoute
  '/scholarships/compare': typeof ScholarshipsCompareRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/scholarships/country/$country': typeof ScholarshipsCountryCountryRoute
  '/scholarships/degree/$degree': typeof ScholarshipsDegreeDegreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/scholarships/closing-soon': typeof ScholarshipsClosingSoonRoute
  '/scholarships/compare': typeof ScholarshipsCompareRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/scholarships/country/$country': typeof ScholarshipsCountryCountryRoute
  '/scholarships/degree/$degree': typeof ScholarshipsDegreeDegreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/og'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/collections/$slug'
    | '/scholarships/$slug'
    | '/scholarships/closing-soon'
    | '/scholarships/compare'
    | '/admin/'
    | '/collections/'
    | '/scholarships/'
    | '/scholarships/country/$country'
    | '/scholarships/degree/$degree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/og'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/collections/$slug'
    | '/scholarships/$slug'
    | '/scholarships/closing-soon'
    | '/scholarships/compare'
    | '/admin'
    | '/collections'
    | '/scholarships'
    | '/scholarships/country/$country'
    | '/scholarships/degree/$degree'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/og'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/collections/$slug'
    | '/scholarships/$slug'
    | '/scholarships/closing-soon'
    | '/scholarships/compare'
    | '/admin/'
    | '/collections/'
    | '/scholarships/'
    | '/scholarships/country/$country'
    | '/scholarships/degree/$degree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
  ScholarshipsClosingSoonRoute: typeof ScholarshipsClosingSoonRoute
  ScholarshipsCompareRoute: typeof ScholarshipsCompareRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
  ScholarshipsCountryCountryRoute: typeof ScholarshipsCountryCountryRoute
  ScholarshipsDegreeDegreeRoute: typeof ScholarshipsDegreeDegreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships/'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/scholarships/compare': {
      id: '/scholarships/compare'
      path: '/scholarships/compare'
      fullPath: '/scholarships/compare'
      preLoaderRoute: typeof ScholarshipsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/closing-soon': {
      id: '/scholarships/closing-soon'
      path: '/scholarships/closing-soon'
      fullPath: '/scholarships/closing-soon'
      preLoaderRoute: typeof ScholarshipsClosingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/scholarships/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/degree/$degree': {
      id: '/scholarships/degree/$degree'
      path: '/scholarships/degree/$degree'
      fullPath: '/scholarships/degree/$degree'
      preLoaderRoute: typeof ScholarshipsDegreeDegreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/country/$country': {
      id: '/scholarships/country/$country'
      path: '/scholarships/country/$country'
      fullPath: '/scholarships/country/$country'
      preLoaderRoute: typeof ScholarshipsCountryCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
  ScholarshipsClosingSoonRoute: ScholarshipsClosingSoonRoute,
  ScholarshipsCompareRoute: ScholarshipsCompareRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
  ScholarshipsCountryCountryRoute: ScholarshipsCountryCountryRoute,
  ScholarshipsDegreeDegreeRoute: ScholarshipsDegreeDegreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
